controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    bike_controller:
      type: bicycle_steering_controller/BicycleSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

bike_controller:
  ros__parameters:
    reference_timeout: 2.0
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false

    base_frame_id: base_link
    traction_joints_names: [drive_joint]
    steering_joints_names: [steering_joint]

    wheelbase: 0.281
    traction_wheel_radius: 0.115

    odom_frame_id: odom
    enable_odom_tf: true
    
