<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>redcat</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="ksementilli@hotmail.ca">legion5</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- urdf -->
  <depend>xacro</depend>

  <!-- ros2_control -->
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>controller_manager</depend>
  <depend>ros2_controllers</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>

  <!-- slam_toolboox and nav2 -->
  <depend>slam_toolbox</depend>
  <depend>navigation2</depend>
  <depend>nav2_bringup</depend>

  <!-- teleoperation -->
  <depend>twist_mux</depend>
  <depend>joy</depend>
  <depend>teleop_twist_joy</depend>

  <!-- lidar dependencies -->
  <exec_depend>unitree_lidar_ros2</exec_depend>
  <depend>robot_localization</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
